function P = runPowerAnalysis(param)
    disp('Running power analysis... Please wait.');
    timeStep = mean(diff(seconds(param.solarLight.time))); % seconds
    for i=1:height(param.solarLight)
        % Power generated by solar cells at each time step
        P(i,1) = calculatePowerGeneration(param.solarLight(i,:), param);
        % Power consumed by the payload at each time step
        P(i,2) = param.power(7);
        % Net power at each time step
        P(i,3) = P(i,1) - P(i,2);
    end
    % Accumulated Energy over time (Wh)
    P(:,4) = cumsum(P(:,3)*timeStep/3600);
    P = array2table([seconds(param.solarLight.time),P]);
    P.Properties.VariableNames = {'time','power_solarCell','power_payload','net_power','accum_energyWh'};
    P.time = seconds(P.time);
    P = table2timetable(P);
    disp('Power analysis completed.');
end